package vn.vnpttech.ssdc.nms.xmpp.model;
// Generated Jun 3, 2015 3:15:47 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Rosterusers generated by hbm2java
 */
public class Rosterusers implements java.io.Serializable {

    private Long id;
    private String username;
    private String jid;
    private String nick;
    private char subscription;
    private char ask;
    private String askmessage;
    private char server;
    private String subscribe;
    private String type;
    private Date createdAt;

    public Rosterusers() {
    }

    public Rosterusers(String username, String jid, String nick, char subscription, char ask, String askmessage, char server, String subscribe, Date createdAt) {
        this.username = username;
        this.jid = jid;
        this.nick = nick;
        this.subscription = subscription;
        this.ask = ask;
        this.askmessage = askmessage;
        this.server = server;
        this.subscribe = subscribe;
        this.createdAt = createdAt;
    }

    public Rosterusers(String username, String jid, String nick, char subscription, char ask, String askmessage, char server, String subscribe, String type, Date createdAt) {
        this.username = username;
        this.jid = jid;
        this.nick = nick;
        this.subscription = subscription;
        this.ask = ask;
        this.askmessage = askmessage;
        this.server = server;
        this.subscribe = subscribe;
        this.type = type;
        this.createdAt = createdAt;
    }

    public Rosterusers(String username, String jid, Date createdAt) {
        this.username = username;
        this.jid = jid;
        this.nick = jid;
        this.subscription = "B".toCharArray()[0];
        this.ask = "N".toCharArray()[0];
        this.askmessage = "";
        this.server = "N".toCharArray()[0];
        this.subscribe = "";
        this.type = "item";
        this.createdAt = createdAt == null ? new Date() : createdAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getJid() {
        return this.jid;
    }

    public void setJid(String jid) {
        this.jid = jid;
    }

    public String getNick() {
        return this.nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public char getSubscription() {
        return this.subscription;
    }

    public void setSubscription(char subscription) {
        this.subscription = subscription;
    }

    public char getAsk() {
        return this.ask;
    }

    public void setAsk(char ask) {
        this.ask = ask;
    }

    public String getAskmessage() {
        return this.askmessage;
    }

    public void setAskmessage(String askmessage) {
        this.askmessage = askmessage;
    }

    public char getServer() {
        return this.server;
    }

    public void setServer(char server) {
        this.server = server;
    }

    public String getSubscribe() {
        return this.subscribe;
    }

    public void setSubscribe(String subscribe) {
        this.subscribe = subscribe;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

}
