package vn.vnpttech.ssdc.nms.xmpp.model;
// Generated Jun 3, 2015 3:15:47 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long id;
     private String username;
     private String password;
     private Date createdAt;

    public Users() {
    }

    public Users(String username, String password, Date createdAt) {
       this.username = username;
       this.password = password;
       this.createdAt = createdAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


