
package vn.vnpttech.ssdc.nms.acs.gpontool.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ACSService", targetNamespace = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ACSService {


    /**
     * 
     * @param simpleObject
     * @param serialNumber
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setValueRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setValueResponse")
    public BasicResponse setValue(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "simpleObject", partName = "simpleObject")
        ArrayList simpleObject);

    /**
     * 
     * @param connectionRequest
     * @param serialNumber
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.DeviceInfoResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/getDeviceInfoRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/getDeviceInfoResponse")
    public DeviceInfoResponse getDeviceInfo(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest);

    /**
     * 
     * @param path
     * @param serialNumber
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/deleteObjectRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/deleteObjectResponse")
    public BasicResponse deleteObject(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "path", partName = "path")
        String path);

    /**
     * 
     * @param connectionRequest
     * @param serialNumber
     * @param dataTree
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/getDataTreeRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/getDataTreeResponse")
    public BasicResponse getDataTree(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "dataTree", partName = "dataTree")
        String dataTree,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest);

    /**
     * 
     * @param userName
     * @param serialNumber
     * @param authenticationURL
     * @param password
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setUserAccountRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setUserAccountResponse")
    public BasicResponse setUserAccount(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "authenticationURL", partName = "authenticationURL")
        String authenticationURL);

    /**
     * 
     * @param connectionRequest
     * @param serialNumber
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/rebootDeviceRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/rebootDeviceResponse")
    public BasicResponse rebootDevice(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest);

    /**
     * 
     * @param serialNumber
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/getCPEStatusRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/getCPEStatusResponse")
    public BasicResponse getCPEStatus(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber);

    /**
     * 
     * @param gateway
     * @param serialNumber
     * @param connectionRequest
     * @param interfacename
     * @param subnetMask
     * @param destination
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setStaticRouteRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setStaticRouteResponse")
    public BasicResponse setStaticRoute(
        @WebParam(name = "destination", partName = "destination")
        String destination,
        @WebParam(name = "subnetMask", partName = "subnetMask")
        String subnetMask,
        @WebParam(name = "interfacename", partName = "interfacename")
        String interfacename,
        @WebParam(name = "gateway", partName = "gateway")
        String gateway,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest,
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber);

    /**
     * 
     * @param usernameFileServer
     * @param connectionRequest
     * @param serialNumber
     * @param passwordFileServer
     * @param version
     * @param fileUrl
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/upgradeFirmwareRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/upgradeFirmwareResponse")
    public BasicResponse upgradeFirmware(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest,
        @WebParam(name = "fileUrl", partName = "fileUrl")
        String fileUrl,
        @WebParam(name = "version", partName = "version")
        String version,
        @WebParam(name = "usernameFileServer", partName = "usernameFileServer")
        String usernameFileServer,
        @WebParam(name = "passwordFileServer", partName = "passwordFileServer")
        String passwordFileServer);

    /**
     * 
     * @param policyId
     * @param usernameFileServer
     * @param serialNumber
     * @param deviceInfo
     * @param passwordFileServer
     * @param version
     * @param fileUrl
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/upgradeFirmwareByPolicyRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/upgradeFirmwareByPolicyResponse")
    public BasicResponse upgradeFirmwareByPolicy(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "fileUrl", partName = "fileUrl")
        String fileUrl,
        @WebParam(name = "version", partName = "version")
        String version,
        @WebParam(name = "usernameFileServer", partName = "usernameFileServer")
        String usernameFileServer,
        @WebParam(name = "passwordFileServer", partName = "passwordFileServer")
        String passwordFileServer,
        @WebParam(name = "policyId", partName = "policyId")
        long policyId,
        @WebParam(name = "deviceInfo", partName = "deviceInfo")
        DeviceInfo deviceInfo);

    /**
     * 
     * @param connectionRequest
     * @param serialNumber
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setDefaulGatewayDNSRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setDefaulGatewayDNSResponse")
    public BasicResponse setDefaulGatewayDNS(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest);

    /**
     * 
     * @param interval
     * @param connectionRequest
     * @param serialNumber
     * @param acsUrl
     * @return
     *     returns vn.vnpttech.ssdc.nms.acs.gpontool.BasicResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setIntervalAcsUrlRequest", output = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/ACSService/setIntervalAcsUrlResponse")
    public BasicResponse setIntervalAcsUrl(
        @WebParam(name = "serialNumber", partName = "serialNumber")
        String serialNumber,
        @WebParam(name = "acsUrl", partName = "acsUrl")
        String acsUrl,
        @WebParam(name = "connectionRequest", partName = "connectionRequest")
        String connectionRequest,
        @WebParam(name = "interval", partName = "interval")
        int interval);

}
