

package vn.vnpttech.ssdc.nms.acs.gpontool.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ACSServiceImplService", targetNamespace = "http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/", wsdlLocation = "http://localhost:82/acsService?wsdl")
public class ACSServiceImplService
    extends Service
{

    private final static URL ACSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ACSSERVICEIMPLSERVICE_QNAME = new QName("http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/", "ACSServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:82/acsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ACSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ACSServiceImplService() {
        super(__getWsdlLocation(), ACSSERVICEIMPLSERVICE_QNAME);
    }

    public ACSServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ACSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ACSSERVICEIMPLSERVICE_QNAME);
    }

    public ACSServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACSSERVICEIMPLSERVICE_QNAME, features);
    }

    public ACSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ACSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ACSService
     */
    @WebEndpoint(name = "ACSServiceImplPort")
    public ACSService getACSServiceImplPort() {
        return super.getPort(new QName("http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/", "ACSServiceImplPort"), ACSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ACSService
     */
    @WebEndpoint(name = "ACSServiceImplPort")
    public ACSService getACSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.stbacs.mediation.nms.ssdc.vnpttech.vn/", "ACSServiceImplPort"), ACSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ACSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ACSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
